# Auto-generated typed stub for OpenFHE
from typing import Any, List, Dict, Overload, Union, overload

class BINFHE_METHOD:
    def AP(self, *args: Any, **kwargs: Any) -> Any: ...

    def GINX(self, *args: Any, **kwargs: Any) -> Any: ...

    def INVALID_METHOD(self, *args: Any, **kwargs: Any) -> Any: ...

    def LMKCDEY(self, *args: Any, **kwargs: Any) -> Any: ...

    def __init__(self: BINFHE_METHOD, value: int) -> None: ...

    def _pybind11_conduit_v1_(self, *args: Any, **kwargs: Any) -> Any: ...

    def name(self, /) -> str: ...

    def value(self, *args: Any, **kwargs: Any) -> Any: ...


class BINFHE_OUTPUT:
    def BOOTSTRAPPED(self, *args: Any, **kwargs: Any) -> Any: ...

    def FRESH(self, *args: Any, **kwargs: Any) -> Any: ...

    def INVALID_OUTPUT(self, *args: Any, **kwargs: Any) -> Any: ...

    def LARGE_DIM(self, *args: Any, **kwargs: Any) -> Any: ...

    def SMALL_DIM(self, *args: Any, **kwargs: Any) -> Any: ...

    def __init__(self: BINFHE_OUTPUT, value: int) -> None: ...

    def _pybind11_conduit_v1_(self, *args: Any, **kwargs: Any) -> Any: ...

    def name(self, /) -> str: ...

    def value(self, *args: Any, **kwargs: Any) -> Any: ...


class BINFHE_PARAMSET:
    def MEDIUM(self, *args: Any, **kwargs: Any) -> Any: ...

    def SIGNED_MOD_TEST(self, *args: Any, **kwargs: Any) -> Any: ...

    def STD128(self, *args: Any, **kwargs: Any) -> Any: ...

    def STD128Q(self, *args: Any, **kwargs: Any) -> Any: ...

    def STD128Q_3(self, *args: Any, **kwargs: Any) -> Any: ...

    def STD128Q_3_LMKCDEY(self, *args: Any, **kwargs: Any) -> Any: ...

    def STD128Q_4(self, *args: Any, **kwargs: Any) -> Any: ...

    def STD128Q_4_LMKCDEY(self, *args: Any, **kwargs: Any) -> Any: ...

    def STD128Q_LMKCDEY(self, *args: Any, **kwargs: Any) -> Any: ...

    def STD128_3(self, *args: Any, **kwargs: Any) -> Any: ...

    def STD128_3_LMKCDEY(self, *args: Any, **kwargs: Any) -> Any: ...

    def STD128_4(self, *args: Any, **kwargs: Any) -> Any: ...

    def STD128_4_LMKCDEY(self, *args: Any, **kwargs: Any) -> Any: ...

    def STD128_AP(self, *args: Any, **kwargs: Any) -> Any: ...

    def STD128_LMKCDEY(self, *args: Any, **kwargs: Any) -> Any: ...

    def STD192(self, *args: Any, **kwargs: Any) -> Any: ...

    def STD192Q(self, *args: Any, **kwargs: Any) -> Any: ...

    def STD192Q_3(self, *args: Any, **kwargs: Any) -> Any: ...

    def STD192Q_4(self, *args: Any, **kwargs: Any) -> Any: ...

    def STD256(self, *args: Any, **kwargs: Any) -> Any: ...

    def STD256Q(self, *args: Any, **kwargs: Any) -> Any: ...

    def STD256Q_3(self, *args: Any, **kwargs: Any) -> Any: ...

    def STD256Q_4(self, *args: Any, **kwargs: Any) -> Any: ...

    def TOY(self, *args: Any, **kwargs: Any) -> Any: ...

    def __init__(self: BINFHE_PARAMSET, value: int) -> None: ...

    def _pybind11_conduit_v1_(self, *args: Any, **kwargs: Any) -> Any: ...

    def name(self, /) -> str: ...

    def value(self, *args: Any, **kwargs: Any) -> Any: ...


class BINGATE:
    def AND(self, *args: Any, **kwargs: Any) -> Any: ...

    def NAND(self, *args: Any, **kwargs: Any) -> Any: ...

    def NOR(self, *args: Any, **kwargs: Any) -> Any: ...

    def OR(self, *args: Any, **kwargs: Any) -> Any: ...

    def XNOR(self, *args: Any, **kwargs: Any) -> Any: ...

    def XNOR_FAST(self, *args: Any, **kwargs: Any) -> Any: ...

    def XOR(self, *args: Any, **kwargs: Any) -> Any: ...

    def XOR_FAST(self, *args: Any, **kwargs: Any) -> Any: ...

    def __init__(self: BINGATE, value: int) -> None: ...

    def _pybind11_conduit_v1_(self, *args: Any, **kwargs: Any) -> Any: ...

    def name(self, /) -> str: ...

    def value(self, *args: Any, **kwargs: Any) -> Any: ...


class BinFHEContext:
    def BTKeyGen(self: BinFHEContext, sk: LWEPrivateKey, keygenMode: KEYGEN_MODE = ...) -> None: ...

    def Bootstrap(self: BinFHEContext, ct: LWECiphertext, extended: bool = ...) -> LWECiphertext: ...

    def ClearBTKeys(self: BinFHEContext) -> None: ...

    def Decrypt(self: BinFHEContext, sk: LWEPrivateKey, ct: LWECiphertext, p: int = ...) -> int: ...

    def Encrypt(self: BinFHEContext, sk: LWEPrivateKey, m: int, output: BINFHE_OUTPUT = ..., p: int = ..., mod: int = ...) -> LWECiphertext: ...

    @overload
    def EvalBinGate(self: BinFHEContext, gate: BINGATE, ct1: LWECiphertext, ct2: LWECiphertext, extended: bool = ...) -> LWECiphertext: ...
    @overload
    def EvalBinGate(self: BinFHEContext, gate: BINGATE, ctvector: List[LWECiphertext], extended: bool = ...) -> LWECiphertext: ...

    def EvalConstant(self: BinFHEContext, arg0: bool) -> LWECiphertext: ...

    def EvalDecomp(self: BinFHEContext, ct: LWECiphertext) -> list[LWECiphertext]: ...

    def EvalFloor(self: BinFHEContext, ct: LWECiphertext, roundbits: int = ...) -> LWECiphertext: ...

    def EvalFunc(self: BinFHEContext, ct: LWECiphertext, LUT: List[int]) -> LWECiphertext: ...

    def EvalNOT(self: BinFHEContext, ct: LWECiphertext) -> LWECiphertext: ...

    def EvalSign(self: BinFHEContext, ct: LWECiphertext, schemeSwitch: bool = ...) -> LWECiphertext: ...

    @overload
    def GenerateBinFHEContext(self: BinFHEContext, set: BINFHE_PARAMSET, method: BINFHE_METHOD = ...) -> None: ...
    @overload
    def GenerateBinFHEContext(self: BinFHEContext, set: BINFHE_PARAMSET, arbFunc: bool, logQ: int = ..., N: int = ..., method: BINFHE_METHOD = ..., timeOptimization: bool = ...) -> None: ...

    def GenerateLUTviaFunction(self: BinFHEContext, f: collections.abc.Callable, p: int) -> list[int]: ...

    def GetBeta(self: BinFHEContext) -> int: ...

    def GetBinFHEScheme(self: BinFHEContext) -> lbcrypto::BinFHEScheme: ...

    def GetLWEScheme(self: BinFHEContext) -> lbcrypto::LWEEncryptionScheme: ...

    def GetMaxPlaintextSpace(self: BinFHEContext) -> int: ...

    def GetParams(self: BinFHEContext) -> lbcrypto::BinFHECryptoParams: ...

    def GetPublicKey(self: BinFHEContext) -> lbcrypto::LWEPublicKeyImpl: ...

    def GetRefreshKey(self: BinFHEContext) -> lbcrypto::RingGSWACCKeyImpl: ...

    def GetSwitchKey(self: BinFHEContext) -> lbcrypto::LWESwitchingKeyImpl: ...

    def Getn(self: BinFHEContext) -> int: ...

    def Getq(self: BinFHEContext) -> int: ...

    def KeyGen(self: BinFHEContext) -> LWEPrivateKey: ...

    def KeyGenN(self: BinFHEContext) -> LWEPrivateKey: ...

    def KeyGenPair(self: BinFHEContext) -> lbcrypto::LWEKeyPairImpl: ...

    def LoadBinary(self: BinFHEContext, arg0: cereal::BinaryInputArchive, arg1: int) -> None: ...

    def LoadJSON(self: BinFHEContext, arg0: cereal::JSONInputArchive, arg1: int) -> None: ...

    def LoadPortableBinary(self: BinFHEContext, arg0: cereal::PortableBinaryInputArchive, arg1: int) -> None: ...

    def SaveBinary(self: BinFHEContext, arg0: cereal::BinaryOutputArchive, arg1: int) -> None: ...

    def SaveJSON(self: BinFHEContext, arg0: cereal::JSONOutputArchive, arg1: int) -> None: ...

    def SavePortableBinary(self: BinFHEContext, arg0: cereal::PortableBinaryOutputArchive, arg1: int) -> None: ...

    def SerializedObjectName(self: BinFHEContext) -> str: ...

    def SerializedVersion() -> int: ...

    def __init__(self: BinFHEContext) -> None: ...

    def _pybind11_conduit_v1_(self, *args: Any, **kwargs: Any) -> Any: ...


class CCParamsBFVRNS:
    def GetBatchSize(self: CCParamsBFVRNS) -> int: ...

    def GetCKKSDataType(self: CCParamsBFVRNS) -> CKKSDataType: ...

    def GetCompositeDegree(self: CCParamsBFVRNS) -> int: ...

    def GetDecryptionNoiseMode(self: CCParamsBFVRNS) -> DecryptionNoiseMode: ...

    def GetDesiredPrecision(self: CCParamsBFVRNS) -> float: ...

    def GetDigitSize(self: CCParamsBFVRNS) -> int: ...

    def GetEncryptionTechnique(self: CCParamsBFVRNS) -> EncryptionTechnique: ...

    def GetEvalAddCount(self: CCParamsBFVRNS) -> int: ...

    def GetExecutionMode(self: CCParamsBFVRNS) -> ExecutionMode: ...

    def GetFirstModSize(self: CCParamsBFVRNS) -> int: ...

    def GetInteractiveBootCompressionLevel(self: CCParamsBFVRNS) -> CompressionLevel: ...

    def GetKeySwitchCount(self: CCParamsBFVRNS) -> int: ...

    def GetKeySwitchTechnique(self: CCParamsBFVRNS) -> KeySwitchTechnique: ...

    def GetMaxRelinSkDeg(self: CCParamsBFVRNS) -> int: ...

    def GetMultipartyMode(self: CCParamsBFVRNS) -> MultipartyMode: ...

    def GetMultiplicationTechnique(self: CCParamsBFVRNS) -> MultiplicationTechnique: ...

    def GetMultiplicativeDepth(self: CCParamsBFVRNS) -> int: ...

    def GetNoiseEstimate(self: CCParamsBFVRNS) -> float: ...

    def GetNumAdversarialQueries(self: CCParamsBFVRNS) -> float: ...

    def GetNumLargeDigits(self: CCParamsBFVRNS) -> int: ...

    def GetPREMode(self: CCParamsBFVRNS) -> ProxyReEncryptionMode: ...

    def GetPRENumHops(self: CCParamsBFVRNS) -> int: ...

    def GetPlaintextModulus(self: CCParamsBFVRNS) -> int: ...

    def GetRegisterWordSize(self: CCParamsBFVRNS) -> int: ...

    def GetRingDim(self: CCParamsBFVRNS) -> int: ...

    def GetScalingModSize(self: CCParamsBFVRNS) -> int: ...

    def GetScalingTechnique(self: CCParamsBFVRNS) -> ScalingTechnique: ...

    def GetScheme(self: CCParamsBFVRNS) -> SCHEME: ...

    def GetSecretKeyDist(self: CCParamsBFVRNS) -> SecretKeyDist: ...

    def GetSecurityLevel(self: CCParamsBFVRNS) -> SecurityLevel: ...

    def GetStandardDeviation(self: CCParamsBFVRNS) -> float: ...

    def GetStatisticalSecurity(self: CCParamsBFVRNS) -> float: ...

    def SetBatchSize(self: CCParamsBFVRNS, arg0: int) -> None: ...

    def SetCKKSDataType(self: CCParamsBFVRNS, arg0: CKKSDataType) -> None: ...

    def SetCompositeDegree(self: CCParamsBFVRNS, arg0: int) -> None: ...

    def SetDecryptionNoiseMode(self: CCParamsBFVRNS, arg0: DecryptionNoiseMode) -> None: ...

    def SetDesiredPrecision(self: CCParamsBFVRNS, arg0: float) -> None: ...

    def SetDigitSize(self: CCParamsBFVRNS, arg0: int) -> None: ...

    def SetEncryptionTechnique(self: CCParamsBFVRNS, arg0: EncryptionTechnique) -> None: ...

    def SetEvalAddCount(self: CCParamsBFVRNS, arg0: int) -> None: ...

    def SetExecutionMode(self: CCParamsBFVRNS, arg0: ExecutionMode) -> None: ...

    def SetFirstModSize(self: CCParamsBFVRNS, arg0: int) -> None: ...

    def SetInteractiveBootCompressionLevel(self: CCParamsBFVRNS, arg0: CompressionLevel) -> None: ...

    def SetKeySwitchCount(self: CCParamsBFVRNS, arg0: int) -> None: ...

    def SetKeySwitchTechnique(self: CCParamsBFVRNS, arg0: KeySwitchTechnique) -> None: ...

    def SetMaxRelinSkDeg(self: CCParamsBFVRNS, arg0: int) -> None: ...

    def SetMultipartyMode(self: CCParamsBFVRNS, arg0: MultipartyMode) -> None: ...

    def SetMultiplicationTechnique(self: CCParamsBFVRNS, arg0: MultiplicationTechnique) -> None: ...

    def SetMultiplicativeDepth(self: CCParamsBFVRNS, arg0: int) -> None: ...

    def SetNoiseEstimate(self: CCParamsBFVRNS, arg0: float) -> None: ...

    def SetNumAdversarialQueries(self: CCParamsBFVRNS, arg0: int) -> None: ...

    def SetNumLargeDigits(self: CCParamsBFVRNS, arg0: int) -> None: ...

    def SetPREMode(self: CCParamsBFVRNS, arg0: ProxyReEncryptionMode) -> None: ...

    def SetPRENumHops(self: CCParamsBFVRNS, arg0: int) -> None: ...

    def SetPlaintextModulus(self: CCParamsBFVRNS, arg0: int) -> None: ...

    def SetRegisterWordSize(self: CCParamsBFVRNS, arg0: int) -> None: ...

    def SetRingDim(self: CCParamsBFVRNS, arg0: int) -> None: ...

    def SetScalingModSize(self: CCParamsBFVRNS, arg0: int) -> None: ...

    def SetScalingTechnique(self: CCParamsBFVRNS, arg0: ScalingTechnique) -> None: ...

    def SetSecretKeyDist(self: CCParamsBFVRNS, arg0: SecretKeyDist) -> None: ...

    def SetSecurityLevel(self: CCParamsBFVRNS, arg0: SecurityLevel) -> None: ...

    def SetStandardDeviation(self: CCParamsBFVRNS, arg0: float) -> None: ...

    def SetStatisticalSecurity(self: CCParamsBFVRNS, arg0: int) -> None: ...

    def SetThresholdNumOfParties(self: CCParamsBFVRNS, arg0: int) -> None: ...

    def __init__(self: CCParamsBFVRNS) -> None: ...

    def _pybind11_conduit_v1_(self, *args: Any, **kwargs: Any) -> Any: ...


class CCParamsBGVRNS:
    def GetBatchSize(self: CCParamsBGVRNS) -> int: ...

    def GetCKKSDataType(self: CCParamsBGVRNS) -> CKKSDataType: ...

    def GetCompositeDegree(self: CCParamsBGVRNS) -> int: ...

    def GetDecryptionNoiseMode(self: CCParamsBGVRNS) -> DecryptionNoiseMode: ...

    def GetDesiredPrecision(self: CCParamsBGVRNS) -> float: ...

    def GetDigitSize(self: CCParamsBGVRNS) -> int: ...

    def GetEncryptionTechnique(self: CCParamsBGVRNS) -> EncryptionTechnique: ...

    def GetEvalAddCount(self: CCParamsBGVRNS) -> int: ...

    def GetExecutionMode(self: CCParamsBGVRNS) -> ExecutionMode: ...

    def GetFirstModSize(self: CCParamsBGVRNS) -> int: ...

    def GetInteractiveBootCompressionLevel(self: CCParamsBGVRNS) -> CompressionLevel: ...

    def GetKeySwitchCount(self: CCParamsBGVRNS) -> int: ...

    def GetKeySwitchTechnique(self: CCParamsBGVRNS) -> KeySwitchTechnique: ...

    def GetMaxRelinSkDeg(self: CCParamsBGVRNS) -> int: ...

    def GetMultipartyMode(self: CCParamsBGVRNS) -> MultipartyMode: ...

    def GetMultiplicationTechnique(self: CCParamsBGVRNS) -> MultiplicationTechnique: ...

    def GetMultiplicativeDepth(self: CCParamsBGVRNS) -> int: ...

    def GetNoiseEstimate(self: CCParamsBGVRNS) -> float: ...

    def GetNumAdversarialQueries(self: CCParamsBGVRNS) -> float: ...

    def GetNumLargeDigits(self: CCParamsBGVRNS) -> int: ...

    def GetPREMode(self: CCParamsBGVRNS) -> ProxyReEncryptionMode: ...

    def GetPRENumHops(self: CCParamsBGVRNS) -> int: ...

    def GetPlaintextModulus(self: CCParamsBGVRNS) -> int: ...

    def GetRegisterWordSize(self: CCParamsBGVRNS) -> int: ...

    def GetRingDim(self: CCParamsBGVRNS) -> int: ...

    def GetScalingModSize(self: CCParamsBGVRNS) -> int: ...

    def GetScalingTechnique(self: CCParamsBGVRNS) -> ScalingTechnique: ...

    def GetScheme(self: CCParamsBGVRNS) -> SCHEME: ...

    def GetSecretKeyDist(self: CCParamsBGVRNS) -> SecretKeyDist: ...

    def GetSecurityLevel(self: CCParamsBGVRNS) -> SecurityLevel: ...

    def GetStandardDeviation(self: CCParamsBGVRNS) -> float: ...

    def GetStatisticalSecurity(self: CCParamsBGVRNS) -> float: ...

    def SetBatchSize(self: CCParamsBGVRNS, arg0: int) -> None: ...

    def SetCKKSDataType(self: CCParamsBGVRNS, arg0: CKKSDataType) -> None: ...

    def SetCompositeDegree(self: CCParamsBGVRNS, arg0: int) -> None: ...

    def SetDecryptionNoiseMode(self: CCParamsBGVRNS, arg0: DecryptionNoiseMode) -> None: ...

    def SetDesiredPrecision(self: CCParamsBGVRNS, arg0: float) -> None: ...

    def SetDigitSize(self: CCParamsBGVRNS, arg0: int) -> None: ...

    def SetEncryptionTechnique(self: CCParamsBGVRNS, arg0: EncryptionTechnique) -> None: ...

    def SetEvalAddCount(self: CCParamsBGVRNS, arg0: int) -> None: ...

    def SetExecutionMode(self: CCParamsBGVRNS, arg0: ExecutionMode) -> None: ...

    def SetFirstModSize(self: CCParamsBGVRNS, arg0: int) -> None: ...

    def SetInteractiveBootCompressionLevel(self: CCParamsBGVRNS, arg0: CompressionLevel) -> None: ...

    def SetKeySwitchCount(self: CCParamsBGVRNS, arg0: int) -> None: ...

    def SetKeySwitchTechnique(self: CCParamsBGVRNS, arg0: KeySwitchTechnique) -> None: ...

    def SetMaxRelinSkDeg(self: CCParamsBGVRNS, arg0: int) -> None: ...

    def SetMultipartyMode(self: CCParamsBGVRNS, arg0: MultipartyMode) -> None: ...

    def SetMultiplicationTechnique(self: CCParamsBGVRNS, arg0: MultiplicationTechnique) -> None: ...

    def SetMultiplicativeDepth(self: CCParamsBGVRNS, arg0: int) -> None: ...

    def SetNoiseEstimate(self: CCParamsBGVRNS, arg0: float) -> None: ...

    def SetNumAdversarialQueries(self: CCParamsBGVRNS, arg0: int) -> None: ...

    def SetNumLargeDigits(self: CCParamsBGVRNS, arg0: int) -> None: ...

    def SetPREMode(self: CCParamsBGVRNS, arg0: ProxyReEncryptionMode) -> None: ...

    def SetPRENumHops(self: CCParamsBGVRNS, arg0: int) -> None: ...

    def SetPlaintextModulus(self: CCParamsBGVRNS, arg0: int) -> None: ...

    def SetRegisterWordSize(self: CCParamsBGVRNS, arg0: int) -> None: ...

    def SetRingDim(self: CCParamsBGVRNS, arg0: int) -> None: ...

    def SetScalingModSize(self: CCParamsBGVRNS, arg0: int) -> None: ...

    def SetScalingTechnique(self: CCParamsBGVRNS, arg0: ScalingTechnique) -> None: ...

    def SetSecretKeyDist(self: CCParamsBGVRNS, arg0: SecretKeyDist) -> None: ...

    def SetSecurityLevel(self: CCParamsBGVRNS, arg0: SecurityLevel) -> None: ...

    def SetStandardDeviation(self: CCParamsBGVRNS, arg0: float) -> None: ...

    def SetStatisticalSecurity(self: CCParamsBGVRNS, arg0: int) -> None: ...

    def SetThresholdNumOfParties(self: CCParamsBGVRNS, arg0: int) -> None: ...

    def __init__(self: CCParamsBGVRNS) -> None: ...

    def _pybind11_conduit_v1_(self, *args: Any, **kwargs: Any) -> Any: ...


class CCParamsCKKSRNS:
    def GetBatchSize(self: CCParamsCKKSRNS) -> int: ...

    def GetCKKSDataType(self: CCParamsCKKSRNS) -> CKKSDataType: ...

    def GetCompositeDegree(self: CCParamsCKKSRNS) -> int: ...

    def GetDecryptionNoiseMode(self: CCParamsCKKSRNS) -> DecryptionNoiseMode: ...

    def GetDesiredPrecision(self: CCParamsCKKSRNS) -> float: ...

    def GetDigitSize(self: CCParamsCKKSRNS) -> int: ...

    def GetEncryptionTechnique(self: CCParamsCKKSRNS) -> EncryptionTechnique: ...

    def GetEvalAddCount(self: CCParamsCKKSRNS) -> int: ...

    def GetExecutionMode(self: CCParamsCKKSRNS) -> ExecutionMode: ...

    def GetFirstModSize(self: CCParamsCKKSRNS) -> int: ...

    def GetInteractiveBootCompressionLevel(self: CCParamsCKKSRNS) -> CompressionLevel: ...

    def GetKeySwitchCount(self: CCParamsCKKSRNS) -> int: ...

    def GetKeySwitchTechnique(self: CCParamsCKKSRNS) -> KeySwitchTechnique: ...

    def GetMaxRelinSkDeg(self: CCParamsCKKSRNS) -> int: ...

    def GetMultipartyMode(self: CCParamsCKKSRNS) -> MultipartyMode: ...

    def GetMultiplicationTechnique(self: CCParamsCKKSRNS) -> MultiplicationTechnique: ...

    def GetMultiplicativeDepth(self: CCParamsCKKSRNS) -> int: ...

    def GetNoiseEstimate(self: CCParamsCKKSRNS) -> float: ...

    def GetNumAdversarialQueries(self: CCParamsCKKSRNS) -> float: ...

    def GetNumLargeDigits(self: CCParamsCKKSRNS) -> int: ...

    def GetPREMode(self: CCParamsCKKSRNS) -> ProxyReEncryptionMode: ...

    def GetPRENumHops(self: CCParamsCKKSRNS) -> int: ...

    def GetPlaintextModulus(self: CCParamsCKKSRNS) -> int: ...

    def GetRegisterWordSize(self: CCParamsCKKSRNS) -> int: ...

    def GetRingDim(self: CCParamsCKKSRNS) -> int: ...

    def GetScalingModSize(self: CCParamsCKKSRNS) -> int: ...

    def GetScalingTechnique(self: CCParamsCKKSRNS) -> ScalingTechnique: ...

    def GetScheme(self: CCParamsCKKSRNS) -> SCHEME: ...

    def GetSecretKeyDist(self: CCParamsCKKSRNS) -> SecretKeyDist: ...

    def GetSecurityLevel(self: CCParamsCKKSRNS) -> SecurityLevel: ...

    def GetStandardDeviation(self: CCParamsCKKSRNS) -> float: ...

    def GetStatisticalSecurity(self: CCParamsCKKSRNS) -> float: ...

    def SetBatchSize(self: CCParamsCKKSRNS, arg0: int) -> None: ...

    def SetCKKSDataType(self: CCParamsCKKSRNS, arg0: CKKSDataType) -> None: ...

    def SetCompositeDegree(self: CCParamsCKKSRNS, arg0: int) -> None: ...

    def SetDecryptionNoiseMode(self: CCParamsCKKSRNS, arg0: DecryptionNoiseMode) -> None: ...

    def SetDesiredPrecision(self: CCParamsCKKSRNS, arg0: float) -> None: ...

    def SetDigitSize(self: CCParamsCKKSRNS, arg0: int) -> None: ...

    def SetEncryptionTechnique(self: CCParamsCKKSRNS, arg0: EncryptionTechnique) -> None: ...

    def SetEvalAddCount(self: CCParamsCKKSRNS, arg0: int) -> None: ...

    def SetExecutionMode(self: CCParamsCKKSRNS, arg0: ExecutionMode) -> None: ...

    def SetFirstModSize(self: CCParamsCKKSRNS, arg0: int) -> None: ...

    def SetInteractiveBootCompressionLevel(self: CCParamsCKKSRNS, arg0: CompressionLevel) -> None: ...

    def SetKeySwitchCount(self: CCParamsCKKSRNS, arg0: int) -> None: ...

    def SetKeySwitchTechnique(self: CCParamsCKKSRNS, arg0: KeySwitchTechnique) -> None: ...

    def SetMaxRelinSkDeg(self: CCParamsCKKSRNS, arg0: int) -> None: ...

    def SetMultipartyMode(self: CCParamsCKKSRNS, arg0: MultipartyMode) -> None: ...

    def SetMultiplicationTechnique(self: CCParamsCKKSRNS, arg0: MultiplicationTechnique) -> None: ...

    def SetMultiplicativeDepth(self: CCParamsCKKSRNS, arg0: int) -> None: ...

    def SetNoiseEstimate(self: CCParamsCKKSRNS, arg0: float) -> None: ...

    def SetNumAdversarialQueries(self: CCParamsCKKSRNS, arg0: int) -> None: ...

    def SetNumLargeDigits(self: CCParamsCKKSRNS, arg0: int) -> None: ...

    def SetPREMode(self: CCParamsCKKSRNS, arg0: ProxyReEncryptionMode) -> None: ...

    def SetPRENumHops(self: CCParamsCKKSRNS, arg0: int) -> None: ...

    def SetPlaintextModulus(self: CCParamsCKKSRNS, arg0: int) -> None: ...

    def SetRegisterWordSize(self: CCParamsCKKSRNS, arg0: int) -> None: ...

    def SetRingDim(self: CCParamsCKKSRNS, arg0: int) -> None: ...

    def SetScalingModSize(self: CCParamsCKKSRNS, arg0: int) -> None: ...

    def SetScalingTechnique(self: CCParamsCKKSRNS, arg0: ScalingTechnique) -> None: ...

    def SetSecretKeyDist(self: CCParamsCKKSRNS, arg0: SecretKeyDist) -> None: ...

    def SetSecurityLevel(self: CCParamsCKKSRNS, arg0: SecurityLevel) -> None: ...

    def SetStandardDeviation(self: CCParamsCKKSRNS, arg0: float) -> None: ...

    def SetStatisticalSecurity(self: CCParamsCKKSRNS, arg0: int) -> None: ...

    def SetThresholdNumOfParties(self: CCParamsCKKSRNS, arg0: int) -> None: ...

    def __init__(self: CCParamsCKKSRNS) -> None: ...

    def _pybind11_conduit_v1_(self, *args: Any, **kwargs: Any) -> Any: ...


class CKKSDataType:
    def COMPLEX(self, *args: Any, **kwargs: Any) -> Any: ...

    def REAL(self, *args: Any, **kwargs: Any) -> Any: ...

    def __init__(self: CKKSDataType, value: int) -> None: ...

    def _pybind11_conduit_v1_(self, *args: Any, **kwargs: Any) -> Any: ...

    def name(self, /) -> str: ...

    def value(self, *args: Any, **kwargs: Any) -> Any: ...


class Ciphertext:
    def Clone(self: Ciphertext) -> Ciphertext: ...

    def GetCryptoContext(self: Ciphertext) -> lbcrypto::CryptoContextImpl<lbcrypto::DCRTPolyImpl<bigintdyn::mubintvec<bigintdyn::ubint<unsigned long long> > > >: ...

    def GetElements(self: Ciphertext) -> list[DCRTPoly]: ...

    def GetElementsMutable(self: Ciphertext) -> list[DCRTPoly]: ...

    def GetEncodingType(self: Ciphertext) -> lbcrypto::PlaintextEncodings: ...

    def GetKeyTag(self: Ciphertext) -> str: ...

    def GetLevel(self: Ciphertext) -> int: ...

    def GetNoiseScaleDeg(self: Ciphertext) -> int: ...

    def GetScalingFactor(self: Ciphertext) -> float: ...

    def GetSlots(self: Ciphertext) -> int: ...

    def RemoveElement(self: Ciphertext, index: int) -> None: ...

    def SetElements(self: Ciphertext, arg0: List[DCRTPoly]) -> None: ...

    def SetElementsMove(self: Ciphertext, arg0: List[DCRTPoly]) -> None: ...

    def SetLevel(self: Ciphertext, level: int) -> None: ...

    def SetNoiseScaleDeg(self: Ciphertext, arg0: int) -> None: ...

    def SetScalingFactor(self: Ciphertext, arg0: float) -> None: ...

    def SetSlots(self: Ciphertext, arg0: int) -> None: ...

    def __init__(self: Ciphertext) -> None: ...

    def _pybind11_conduit_v1_(self, *args: Any, **kwargs: Any) -> Any: ...


class CompressionLevel:
    def COMPACT(self, *args: Any, **kwargs: Any) -> Any: ...

    def SLACK(self, *args: Any, **kwargs: Any) -> Any: ...

    def __init__(self: CompressionLevel, value: int) -> None: ...

    def _pybind11_conduit_v1_(self, *args: Any, **kwargs: Any) -> Any: ...

    def name(self, /) -> str: ...

    def value(self, *args: Any, **kwargs: Any) -> Any: ...


class CryptoContext:
    def ClearEvalAutomorphismKeys() -> None: ...

    def Compress(self: CryptoContext, ciphertext: Ciphertext, towersLeft: int = ..., noiseScaleDeg: int = ...) -> Ciphertext: ...

    @overload
    def Decrypt(self: CryptoContext, privateKey: PrivateKey, ciphertext: Ciphertext) -> Plaintext: ...
    @overload
    def Decrypt(self: CryptoContext, ciphertext: Ciphertext, privateKey: PrivateKey) -> Plaintext: ...

    @overload
    def DeserializeEvalAutomorphismKey(filename: str, sertype: SERBINARY) -> bool: ...
    @overload
    def DeserializeEvalAutomorphismKey(filename: str, sertype: SERJSON) -> bool: ...

    @overload
    def DeserializeEvalMultKey(filename: str, sertype: SERBINARY) -> bool: ...
    @overload
    def DeserializeEvalMultKey(filename: str, sertype: SERJSON) -> bool: ...

    def Enable(self: CryptoContext, feature: PKESchemeFeature) -> None: ...

    @overload
    def Encrypt(self: CryptoContext, publicKey: PublicKey, plaintext: Plaintext) -> Ciphertext: ...
    @overload
    def Encrypt(self: CryptoContext, privateKey: PrivateKey, plaintext: Plaintext) -> Ciphertext: ...

    @overload
    def EvalAdd(self: CryptoContext, ciphertext1: Ciphertext, ciphertext2: Ciphertext) -> Ciphertext: ...
    @overload
    def EvalAdd(self: CryptoContext, ciphertext: Ciphertext, plaintext: Plaintext) -> Ciphertext: ...
    @overload
    def EvalAdd(self: CryptoContext, plaintext: Plaintext, ciphertext: Ciphertext) -> Ciphertext: ...
    @overload
    def EvalAdd(self: CryptoContext, ciphertext: Ciphertext, scalar: float) -> Ciphertext: ...
    @overload
    def EvalAdd(self: CryptoContext, scalar: float, ciphertext: Ciphertext) -> Ciphertext: ...
    @overload
    def EvalAdd(self: CryptoContext, ciphertext: Ciphertext, scalar: typing.SupportsComplex | float) -> Ciphertext: ...
    @overload
    def EvalAdd(self: CryptoContext, scalar: typing.SupportsComplex | float, ciphertext: Ciphertext) -> Ciphertext: ...

    @overload
    def EvalAddInPlace(self: CryptoContext, ciphertext1: Ciphertext, ciphertext2: Ciphertext) -> None: ...
    @overload
    def EvalAddInPlace(self: CryptoContext, ciphertext: Ciphertext, plaintext: Plaintext) -> None: ...
    @overload
    def EvalAddInPlace(self: CryptoContext, plaintext: Plaintext, ciphertext: Ciphertext) -> None: ...
    @overload
    def EvalAddInPlace(self: CryptoContext, ciphertext: Ciphertext, scalar: float) -> None: ...
    @overload
    def EvalAddInPlace(self: CryptoContext, scalar: float, ciphertext: Ciphertext) -> None: ...
    @overload
    def EvalAddInPlace(self: CryptoContext, ciphertext: Ciphertext, scalar: typing.SupportsComplex | float) -> None: ...
    @overload
    def EvalAddInPlace(self: CryptoContext, scalar: typing.SupportsComplex | float, ciphertext: Ciphertext) -> None: ...
    @overload
    def EvalAddInPlace(self: CryptoContext, ciphertext: Ciphertext, scalar: float) -> None: ...
    @overload
    def EvalAddInPlace(self: CryptoContext, scalar: float, ciphertext: Ciphertext) -> None: ...
    @overload
    def EvalAddInPlace(self: CryptoContext, ciphertext: Ciphertext, scalar: typing.SupportsComplex | float) -> None: ...
    @overload
    def EvalAddInPlace(self: CryptoContext, scalar: typing.SupportsComplex | float, ciphertext: Ciphertext) -> None: ...

    def EvalAddMany(self: CryptoContext, ciphertextVec: List[Ciphertext]) -> Ciphertext: ...

    def EvalAddManyInPlace(self: CryptoContext, ciphertextVec: List[Ciphertext]) -> Ciphertext: ...

    @overload
    def EvalAddMutable(self: CryptoContext, ciphertext1: Ciphertext, ciphertext2: Ciphertext) -> Ciphertext: ...
    @overload
    def EvalAddMutable(self: CryptoContext, ciphertext: Ciphertext, plaintext: Plaintext) -> Ciphertext: ...
    @overload
    def EvalAddMutable(self: CryptoContext, plaintext: Plaintext, ciphertext: Ciphertext) -> Ciphertext: ...

    def EvalAddMutableInPlace(self: CryptoContext, ciphertext1: Ciphertext, ciphertext2: Ciphertext) -> None: ...

    def EvalAtIndex(self: CryptoContext, ciphertext: Ciphertext, index: int) -> Ciphertext: ...

    def EvalAtIndexKeyGen(self: CryptoContext, privateKey: PrivateKey, indexList: List[int]) -> None: ...

    def EvalAutomorphism(self: CryptoContext, ciphertext: Ciphertext, i: int, evalKeyMap: EvalKeyMap) -> Ciphertext: ...

    def EvalAutomorphismKeyGen(self: CryptoContext, privateKey: PrivateKey, indexList: List[int]) -> EvalKeyMap: ...

    def EvalBootstrap(self: CryptoContext, ciphertext: Ciphertext, numIterations: int = ..., precision: int = ...) -> Ciphertext: ...

    def EvalBootstrapKeyGen(self: CryptoContext, privateKey: PrivateKey, slots: int) -> None: ...

    def EvalBootstrapSetup(self: CryptoContext, levelBudget: List[int] = ..., dim1: List[int] = ..., slots: int = ..., correctionFactor: int = ..., precompute: bool = ..., BTSlotsEncoding: bool = ...) -> None: ...

    def EvalCKKStoFHEW(self: CryptoContext, ciphertext: Ciphertext, numCtxts: int = ...) -> list[LWECiphertext]: ...

    def EvalCKKStoFHEWKeyGen(self: CryptoContext, keyPair: KeyPair, lwesk: LWEPrivateKey) -> None: ...

    def EvalCKKStoFHEWPrecompute(self: CryptoContext, scale: float = ...) -> None: ...

    def EvalCKKStoFHEWSetup(self: CryptoContext, schswchparams: lbcrypto::SchSwchParams) -> LWEPrivateKey: ...

    def EvalChebyshevFunction(self: CryptoContext, func: collections.abc.Callable[[float], float], ciphertext: Ciphertext, a: float, b: float, degree: int) -> Ciphertext: ...

    @overload
    def EvalChebyshevSeries(self: CryptoContext, ciphertext: Ciphertext, coefficients: List[int], a: float, b: float) -> Ciphertext: ...
    @overload
    def EvalChebyshevSeries(self: CryptoContext, ciphertext: Ciphertext, coefficients: List[float], a: float, b: float) -> Ciphertext: ...
    @overload
    def EvalChebyshevSeries(self: CryptoContext, ciphertext: Ciphertext, coefficients: List[typing.SupportsComplex | float], a: float, b: float) -> Ciphertext: ...

    @overload
    def EvalChebyshevSeriesLinear(self: CryptoContext, ciphertext: Ciphertext, coefficients: List[int], a: float, b: float) -> Ciphertext: ...
    @overload
    def EvalChebyshevSeriesLinear(self: CryptoContext, ciphertext: Ciphertext, coefficients: List[float], a: float, b: float) -> Ciphertext: ...
    @overload
    def EvalChebyshevSeriesLinear(self: CryptoContext, ciphertext: Ciphertext, coefficients: List[typing.SupportsComplex | float], a: float, b: float) -> Ciphertext: ...

    @overload
    def EvalChebyshevSeriesPS(self: CryptoContext, ciphertext: Ciphertext, coefficients: List[int], a: float, b: float) -> Ciphertext: ...
    @overload
    def EvalChebyshevSeriesPS(self: CryptoContext, ciphertext: Ciphertext, coefficients: List[float], a: float, b: float) -> Ciphertext: ...
    @overload
    def EvalChebyshevSeriesPS(self: CryptoContext, ciphertext: Ciphertext, coefficients: List[typing.SupportsComplex | float], a: float, b: float) -> Ciphertext: ...

    def EvalCompareSchemeSwitching(self: CryptoContext, ciphertext1: Ciphertext, ciphertext2: Ciphertext, numCtxts: int = ..., numSlots: int = ..., pLWE: int = ..., scaleSign: float = ..., unit: bool = ...) -> Ciphertext: ...

    def EvalCompareSwitchPrecompute(self: CryptoContext, pLWE: int = ..., scaleSign: float = ..., unit: bool = ...) -> None: ...

    def EvalCos(self: CryptoContext, ciphertext: Ciphertext, a: float, b: float, degree: int) -> Ciphertext: ...

    def EvalDivide(self: CryptoContext, ciphertext: Ciphertext, a: float, b: float, degree: int) -> Ciphertext: ...

    def EvalFHEWtoCKKS(self: CryptoContext, LWECiphertexts: List[LWECiphertext], numCtxts: int = ..., numSlots: int = ..., p: int = ..., pmin: float = ..., pmax: float = ..., dim1: int = ...) -> Ciphertext: ...

    def EvalFHEWtoCKKSKeyGen(self: CryptoContext, keyPair: KeyPair, lwesk: LWEPrivateKey, numSlots: int = ..., numCtxts: int = ..., dim1: int = ..., L: int = ...) -> None: ...

    def EvalFHEWtoCKKSSetup(self: CryptoContext, ccLWE: BinFHEContext, numSlotsCKKS: int = ..., logQ: int = ...) -> None: ...

    @overload
    def EvalFastRotation(self: CryptoContext, ciphertext: Ciphertext, index: int, m: int, digits: Ciphertext) -> Ciphertext: ...
    @overload
    def EvalFastRotation(self: CryptoContext, ciphertext: Ciphertext, index: int, digits: Ciphertext) -> Ciphertext: ...

    def EvalFastRotationExt(self: CryptoContext, ciphertext: Ciphertext, index: int, digits: Ciphertext, addFirst: bool) -> Ciphertext: ...

    def EvalFastRotationPrecompute(self: CryptoContext, ciphertext: Ciphertext) -> Ciphertext: ...

    @overload
    def EvalInnerProduct(self: CryptoContext, ciphertext1: Ciphertext, ciphertext2: Ciphertext, batchSize: int) -> Ciphertext: ...
    @overload
    def EvalInnerProduct(self: CryptoContext, ciphertext: Ciphertext, plaintext: Plaintext, batchSize: int) -> Ciphertext: ...

    @overload
    def EvalLinearWSum(self: CryptoContext, ciphertextVec: List[Ciphertext], constantVec: List[int]) -> Ciphertext: ...
    @overload
    def EvalLinearWSum(self: CryptoContext, ciphertextVec: List[Ciphertext], constantVec: List[float]) -> Ciphertext: ...
    @overload
    def EvalLinearWSum(self: CryptoContext, ciphertextVec: List[Ciphertext], constantVec: List[typing.SupportsComplex | float]) -> Ciphertext: ...

    @overload
    def EvalLinearWSumMutable(self: CryptoContext, constantsVec: List[int], ciphertextVec: List[Ciphertext]) -> Ciphertext: ...
    @overload
    def EvalLinearWSumMutable(self: CryptoContext, constantsVec: List[float], ciphertextVec: List[Ciphertext]) -> Ciphertext: ...
    @overload
    def EvalLinearWSumMutable(self: CryptoContext, constantsVec: List[typing.SupportsComplex | float], ciphertextVec: List[Ciphertext]) -> Ciphertext: ...

    def EvalLogistic(self: CryptoContext, ciphertext: Ciphertext, a: float, b: float, degree: int) -> Ciphertext: ...

    def EvalMaxSchemeSwitching(self: CryptoContext, ciphertext: Ciphertext, publicKey: PublicKey, numValues: int = ..., numSlots: int = ..., pLWE: int = ..., scaleSign: float = ...) -> list[Ciphertext]: ...

    def EvalMaxSchemeSwitchingAlt(self: CryptoContext, ciphertext: Ciphertext, publicKey: PublicKey, numValues: int = ..., numSlots: int = ..., pLWE: int = ..., scaleSign: float = ...) -> list[Ciphertext]: ...

    def EvalMerge(self: CryptoContext, ciphertextVec: List[Ciphertext]) -> Ciphertext: ...

    def EvalMinSchemeSwitching(self: CryptoContext, ciphertext: Ciphertext, publicKey: PublicKey, numValues: int = ..., numSlots: int = ..., pLWE: int = ..., scaleSign: float = ...) -> list[Ciphertext]: ...

    def EvalMinSchemeSwitchingAlt(self: CryptoContext, ciphertext: Ciphertext, publicKey: PublicKey, numValues: int = ..., numSlots: int = ..., pLWE: int = ..., scaleSign: float = ...) -> list[Ciphertext]: ...

    @overload
    def EvalMult(self: CryptoContext, ciphertext1: Ciphertext, ciphertext2: Ciphertext) -> Ciphertext: ...
    @overload
    def EvalMult(self: CryptoContext, ciphertext: Ciphertext, plaintext: Plaintext) -> Ciphertext: ...
    @overload
    def EvalMult(self: CryptoContext, plaintext: Plaintext, ciphertext: Ciphertext) -> Ciphertext: ...
    @overload
    def EvalMult(self: CryptoContext, ciphertext: Ciphertext, scalar: float) -> Ciphertext: ...
    @overload
    def EvalMult(self: CryptoContext, scalar: float, ciphertext: Ciphertext) -> Ciphertext: ...
    @overload
    def EvalMult(self: CryptoContext, ciphertext: Ciphertext, scalar: typing.SupportsComplex | float) -> Ciphertext: ...
    @overload
    def EvalMult(self: CryptoContext, scalar: typing.SupportsComplex | float, ciphertext: Ciphertext) -> Ciphertext: ...

    def EvalMultAndRelinearize(self: CryptoContext, ciphertext1: Ciphertext, ciphertext2: Ciphertext) -> Ciphertext: ...

    def EvalMultKeyGen(self: CryptoContext, privateKey: PrivateKey) -> None: ...

    def EvalMultKeysGen(self: CryptoContext, privateKey: PrivateKey) -> None: ...

    def EvalMultMany(self: CryptoContext, ciphertextVec: List[Ciphertext]) -> Ciphertext: ...

    @overload
    def EvalMultMutable(self: CryptoContext, ciphertext1: Ciphertext, ciphertext2: Ciphertext) -> Ciphertext: ...
    @overload
    def EvalMultMutable(self: CryptoContext, ciphertext: Ciphertext, plaintext: Plaintext) -> Ciphertext: ...
    @overload
    def EvalMultMutable(self: CryptoContext, plaintext: Plaintext, ciphertext: Ciphertext) -> Ciphertext: ...

    def EvalMultMutableInPlace(self: CryptoContext, ciphertext1: Ciphertext, ciphertext2: Ciphertext) -> None: ...

    def EvalMultNoRelin(self: CryptoContext, ciphertext1: Ciphertext, ciphertext2: Ciphertext) -> Ciphertext: ...

    def EvalNegate(self: CryptoContext, ciphertext: Ciphertext) -> Ciphertext: ...

    def EvalNegateInPlace(self: CryptoContext, ciphertext: Ciphertext) -> None: ...

    @overload
    def EvalPoly(self: CryptoContext, ciphertext: Ciphertext, coefficients: List[int]) -> Ciphertext: ...
    @overload
    def EvalPoly(self: CryptoContext, ciphertext: Ciphertext, coefficients: List[float]) -> Ciphertext: ...
    @overload
    def EvalPoly(self: CryptoContext, ciphertext: Ciphertext, coefficients: List[typing.SupportsComplex | float]) -> Ciphertext: ...

    @overload
    def EvalPolyLinear(self: CryptoContext, ciphertext: Ciphertext, coefficients: List[int]) -> Ciphertext: ...
    @overload
    def EvalPolyLinear(self: CryptoContext, ciphertext: Ciphertext, coefficients: List[float]) -> Ciphertext: ...
    @overload
    def EvalPolyLinear(self: CryptoContext, ciphertext: Ciphertext, coefficients: List[typing.SupportsComplex | float]) -> Ciphertext: ...

    @overload
    def EvalPolyPS(self: CryptoContext, ciphertext: Ciphertext, coefficients: List[int]) -> Ciphertext: ...
    @overload
    def EvalPolyPS(self: CryptoContext, ciphertext: Ciphertext, coefficients: List[float]) -> Ciphertext: ...
    @overload
    def EvalPolyPS(self: CryptoContext, ciphertext: Ciphertext, coefficients: List[typing.SupportsComplex | float]) -> Ciphertext: ...

    def EvalRotate(self: CryptoContext, ciphertext: Ciphertext, index: int) -> Ciphertext: ...

    def EvalRotateKeyGen(self: CryptoContext, privateKey: PrivateKey, indexList: List[int]) -> None: ...

    def EvalSchemeSwitchingKeyGen(self: CryptoContext, keyPair: KeyPair, lwesk: LWEPrivateKey) -> None: ...

    def EvalSchemeSwitchingSetup(self: CryptoContext, schswchparams: lbcrypto::SchSwchParams) -> LWEPrivateKey: ...

    def EvalSin(self: CryptoContext, ciphertext: Ciphertext, a: float, b: float, degree: int) -> Ciphertext: ...

    def EvalSquare(self: CryptoContext, ciphertext: Ciphertext) -> Ciphertext: ...

    def EvalSquareInPlace(self: CryptoContext, ciphertext: Ciphertext) -> None: ...

    def EvalSquareMutable(self: CryptoContext, ciphertext: Ciphertext) -> Ciphertext: ...

    @overload
    def EvalSub(self: CryptoContext, ciphertext1: Ciphertext, ciphertext2: Ciphertext) -> Ciphertext: ...
    @overload
    def EvalSub(self: CryptoContext, ciphertext: Ciphertext, plaintext: Plaintext) -> Ciphertext: ...
    @overload
    def EvalSub(self: CryptoContext, plaintext: Plaintext, ciphertext: Ciphertext) -> Ciphertext: ...
    @overload
    def EvalSub(self: CryptoContext, ciphertext: Ciphertext, scalar: float) -> Ciphertext: ...
    @overload
    def EvalSub(self: CryptoContext, scalar: float, ciphertext: Ciphertext) -> Ciphertext: ...
    @overload
    def EvalSub(self: CryptoContext, ciphertext: Ciphertext, scalar: typing.SupportsComplex | float) -> Ciphertext: ...
    @overload
    def EvalSub(self: CryptoContext, scalar: typing.SupportsComplex | float, ciphertext: Ciphertext) -> Ciphertext: ...

    @overload
    def EvalSubInPlace(self: CryptoContext, ciphertext1: Ciphertext, ciphertext2: Ciphertext) -> None: ...
    @overload
    def EvalSubInPlace(self: CryptoContext, ciphertext: Ciphertext, plaintext: Plaintext) -> None: ...
    @overload
    def EvalSubInPlace(self: CryptoContext, plaintext: Plaintext, ciphertext: Ciphertext) -> None: ...
    @overload
    def EvalSubInPlace(self: CryptoContext, ciphertext: Ciphertext, scalar: float) -> None: ...
    @overload
    def EvalSubInPlace(self: CryptoContext, scalar: float, ciphertext: Ciphertext) -> None: ...
    @overload
    def EvalSubInPlace(self: CryptoContext, ciphertext: Ciphertext, scalar: typing.SupportsComplex | float) -> None: ...
    @overload
    def EvalSubInPlace(self: CryptoContext, scalar: typing.SupportsComplex | float, ciphertext: Ciphertext) -> None: ...

    @overload
    def EvalSubMutable(self: CryptoContext, ciphertext1: Ciphertext, ciphertext2: Ciphertext) -> Ciphertext: ...
    @overload
    def EvalSubMutable(self: CryptoContext, ciphertext: Ciphertext, plaintext: Plaintext) -> Ciphertext: ...
    @overload
    def EvalSubMutable(self: CryptoContext, plaintext: Plaintext, ciphertext: Ciphertext) -> Ciphertext: ...

    def EvalSubMutableInPlace(self: CryptoContext, ciphertext1: Ciphertext, ciphertext2: Ciphertext) -> None: ...

    def EvalSum(self: CryptoContext, ciphertext: Ciphertext, batchSize: int) -> Ciphertext: ...

    def EvalSumCols(self: CryptoContext, ciphertext: Ciphertext, numCols: int, evalSumKeyMap: EvalKeyMap) -> Ciphertext: ...

    def EvalSumColsKeyGen(self: CryptoContext, privateKey: PrivateKey) -> EvalKeyMap: ...

    def EvalSumKeyGen(self: CryptoContext, privateKey: PrivateKey) -> None: ...

    def EvalSumRows(self: CryptoContext, ciphertext: Ciphertext, numRows: int, evalSumKeyMap: EvalKeyMap, subringDim: int = ...) -> Ciphertext: ...

    @overload
    def EvalSumRowsKeyGen(self: CryptoContext, privateKey: PrivateKey, rowSize: int = ..., subringDim: int = ...) -> EvalKeyMap: ...
    @overload
    def EvalSumRowsKeyGen(self: CryptoContext, privateKey: PrivateKey, publicKey: PublicKey, rowSize: int = ..., subringDim: int = ...) -> EvalKeyMap: ...

    def FindAutomorphismIndex(self: CryptoContext, idx: int) -> int: ...

    def FindAutomorphismIndices(self: CryptoContext, idxList: List[int]) -> list[int]: ...

    def GetBatchSize(self: CryptoContext) -> int: ...

    def GetBinCCForSchemeSwitch(self: CryptoContext) -> BinFHEContext: ...

    def GetCKKSBootCorrectionFactor(self: CryptoContext) -> int: ...

    def GetCKKSDataType(self: CryptoContext) -> CKKSDataType: ...

    def GetCompositeDegree(self: CryptoContext) -> int: ...

    def GetCyclotomicOrder(self: CryptoContext) -> int: ...

    def GetDigitSize(self: CryptoContext) -> int: ...

    def GetEvalAddCount(self: CryptoContext) -> int: ...

    def GetEvalAutomorphismKeyMap(keyTag: str = ...) -> EvalKeyMap: ...

    def GetEvalMultKeyVector(keyTag: str = ...) -> list[EvalKey]: ...

    def GetEvalSumKeyMap(self: CryptoContext, keyTag: str) -> EvalKeyMap: ...

    def GetKeyGenLevel(self: CryptoContext) -> int: ...

    def GetKeySwitchCount(self: CryptoContext) -> int: ...

    def GetKeySwitchTechnique(self: CryptoContext) -> KeySwitchTechnique: ...

    def GetModulus(self: CryptoContext) -> float: ...

    def GetModulusCKKS(self: CryptoContext) -> int: ...

    def GetMultiplicativeDepth(self: CryptoContext) -> int: ...

    def GetNoiseEstimate(self: CryptoContext) -> float: ...

    def GetPRENumHops(self: CryptoContext) -> int: ...

    def GetPlaintextModulus(self: CryptoContext) -> int: ...

    def GetRegisterWordSize(self: CryptoContext) -> int: ...

    def GetRingDimension(self: CryptoContext) -> int: ...

    def GetScalingFactorReal(self: CryptoContext, level: int) -> float: ...

    def GetScalingTechnique(self: CryptoContext) -> ScalingTechnique: ...

    def InsertEvalAutomorphismKey(evalKeyMap: EvalKeyMap, keyTag: str = ...) -> None: ...

    def InsertEvalMultKey(evalKeyVec: List[EvalKey], keyTag: str = ...) -> None: ...

    def InsertEvalSumKey(evalKeyMap: EvalKeyMap, keyTag: str = ...) -> None: ...

    def IntBootAdd(self: CryptoContext, ciphertext1: Ciphertext, ciphertext2: Ciphertext) -> Ciphertext: ...

    def IntBootAdjustScale(self: CryptoContext, ciphertext: Ciphertext) -> Ciphertext: ...

    def IntBootDecrypt(self: CryptoContext, privateKey: PrivateKey, ciphertext: Ciphertext) -> Ciphertext: ...

    def IntBootEncrypt(self: CryptoContext, publicKey: PublicKey, ciphertext: Ciphertext) -> Ciphertext: ...

    def IntMPBootAdd(self: CryptoContext, sharePairVec: List[List[Ciphertext]]) -> list[Ciphertext]: ...

    def IntMPBootAdjustScale(self: CryptoContext, ciphertext: Ciphertext) -> Ciphertext: ...

    def IntMPBootDecrypt(self: CryptoContext, privateKey: PrivateKey, ciphertext: Ciphertext, a: Ciphertext) -> list[Ciphertext]: ...

    def IntMPBootEncrypt(self: CryptoContext, publicKey: PublicKey, sharePair: List[Ciphertext], a: Ciphertext, ciphertext: Ciphertext) -> Ciphertext: ...

    @overload
    def IntMPBootRandomElementGen(self: CryptoContext, publicKey: PublicKey) -> Ciphertext: ...
    @overload
    def IntMPBootRandomElementGen(self: CryptoContext, ciphertext: Ciphertext) -> Ciphertext: ...

    def KeyGen(self: CryptoContext) -> KeyPair: ...

    def KeySwitchGen(self: CryptoContext, oldPrivateKey: PrivateKey, newPrivateKey: PrivateKey) -> EvalKey: ...

    @overload
    def MakeCKKSPackedPlaintext(self: CryptoContext, value: List[typing.SupportsComplex | float], noiseScaleDeg: int = ..., level: int = ..., params: ParmType = ..., slots: int = ...) -> Plaintext: ...
    @overload
    def MakeCKKSPackedPlaintext(self: CryptoContext, value: List[float], noiseScaleDeg: int = ..., level: int = ..., params: ParmType = ..., slots: int = ...) -> Plaintext: ...

    def MakeCoefPackedPlaintext(self: CryptoContext, value: List[int], noiseScaleDeg : int = ..., level: int = ...) -> Plaintext: ...

    def MakePackedPlaintext(self: CryptoContext, value: List[int], noiseScaleDeg: int = ..., level: int = ...) -> Plaintext: ...

    def MakeStringPlaintext(self: CryptoContext, str: str) -> Plaintext: ...

    def ModReduce(self: CryptoContext, ciphertext: Ciphertext) -> Ciphertext: ...

    def ModReduceInPlace(self: CryptoContext, ciphertext: Ciphertext) -> None: ...

    def MultiAddEvalAutomorphismKeys(self: CryptoContext, evalKeyMap1: EvalKeyMap, evalKeyMap2: EvalKeyMap, keyTag: str = ...) -> EvalKeyMap: ...

    def MultiAddEvalKeys(self: CryptoContext, evalKey1: EvalKey, evalKey2: EvalKey, keyTag: str = ...) -> EvalKey: ...

    def MultiAddEvalMultKeys(self: CryptoContext, evalKey1: EvalKey, evalKey2: EvalKey, keyTag: str = ...) -> EvalKey: ...

    def MultiAddEvalSumKeys(self: CryptoContext, evalKeyMap1: EvalKeyMap, evalKeyMap2: EvalKeyMap, keyTag: str = ...) -> EvalKeyMap: ...

    def MultiAddPubKeys(self: CryptoContext, publicKey1: PublicKey, publicKey2: PublicKey, keyTag: str = ...) -> PublicKey: ...

    def MultiEvalAtIndexKeyGen(self: CryptoContext, privateKey: PrivateKey, evalKeyMap: EvalKeyMap, indexList: List[int], keyTag: str = ...) -> EvalKeyMap: ...

    def MultiEvalSumKeyGen(self: CryptoContext, privateKey: PrivateKey, evalKeyMap: EvalKeyMap, keyTag: str = ...) -> EvalKeyMap: ...

    def MultiKeySwitchGen(self: CryptoContext, originalPrivateKey: PrivateKey, newPrivateKey: PrivateKey, evalKey: EvalKey) -> EvalKey: ...

    def MultiMultEvalKey(self: CryptoContext, privateKey: PrivateKey, evalKey: EvalKey, keyTag: str = ...) -> EvalKey: ...

    def MultipartyDecryptFusion(self: CryptoContext, partialCiphertextVec: List[Ciphertext]) -> Plaintext: ...

    def MultipartyDecryptLead(self: CryptoContext, ciphertextVec: List[Ciphertext], privateKey: PrivateKey) -> list[Ciphertext]: ...

    def MultipartyDecryptMain(self: CryptoContext, ciphertextVec: List[Ciphertext], privateKey: PrivateKey) -> list[Ciphertext]: ...

    @overload
    def MultipartyKeyGen(self: CryptoContext, publicKey: PublicKey, makeSparse: bool = ..., fresh: bool = ...) -> KeyPair: ...
    @overload
    def MultipartyKeyGen(self: CryptoContext, privateKeyVec: List[PrivateKey]) -> KeyPair: ...

    def ReEncrypt(self: CryptoContext, ciphertext: Ciphertext, evalKey: EvalKey, publicKey: PublicKey = ...) -> Ciphertext: ...

    def ReKeyGen(self: CryptoContext, oldPrivateKey: PrivateKey, newPublicKey: PublicKey) -> EvalKey: ...

    def Relinearize(self: CryptoContext, ciphertext: Ciphertext) -> Ciphertext: ...

    def RelinearizeInPlace(self: CryptoContext, ciphertext: Ciphertext) -> None: ...

    def Rescale(self: CryptoContext, ciphertext: Ciphertext) -> Ciphertext: ...

    def RescaleInPlace(self: CryptoContext, ciphertext: Ciphertext) -> None: ...

    @overload
    def SerializeEvalAutomorphismKey(filename: str, sertype: SERBINARY, keyTag: str = ...) -> bool: ...
    @overload
    def SerializeEvalAutomorphismKey(filename: str, sertype: SERJSON, keyTag: str = ...) -> bool: ...

    @overload
    def SerializeEvalMultKey(filename: str, sertype: SERBINARY, keyTag: str = ...) -> bool: ...
    @overload
    def SerializeEvalMultKey(filename: str, sertype: SERJSON, keyTag: str = ...) -> bool: ...

    def SetCKKSBootCorrectionFactor(self: CryptoContext, cf: int) -> None: ...

    def SetEvalAddCount(self: CryptoContext, evalAddCount: int) -> None: ...

    def SetKeyGenLevel(self: CryptoContext, level: int) -> None: ...

    def SetKeySwitchCount(self: CryptoContext, keySwitchCount: int) -> None: ...

    def SetMultiplicativeDepth(self: CryptoContext, multiplicativeDepth: int) -> None: ...

    def SetNoiseEstimate(self: CryptoContext, noiseEstimate: float) -> None: ...

    def SetPRENumHops(self: CryptoContext, PRENumHops: int) -> None: ...

    def __init__(self: CryptoContext) -> None: ...

    def _pybind11_conduit_v1_(self, *args: Any, **kwargs: Any) -> Any: ...

    def get_ptr(self: CryptoContext) -> None: ...


class DCRTPoly:
    def __init__(self: DCRTPoly) -> None: ...

    def _pybind11_conduit_v1_(self, *args: Any, **kwargs: Any) -> Any: ...


class DecryptionNoiseMode:
    def FIXED_NOISE_DECRYPT(self, *args: Any, **kwargs: Any) -> Any: ...

    def NOISE_FLOODING_DECRYPT(self, *args: Any, **kwargs: Any) -> Any: ...

    def __init__(self: DecryptionNoiseMode, value: int) -> None: ...

    def _pybind11_conduit_v1_(self, *args: Any, **kwargs: Any) -> Any: ...

    def name(self, /) -> str: ...

    def value(self, *args: Any, **kwargs: Any) -> Any: ...


class EncryptionTechnique:
    def EXTENDED(self, *args: Any, **kwargs: Any) -> Any: ...

    def STANDARD(self, *args: Any, **kwargs: Any) -> Any: ...

    def __init__(self: EncryptionTechnique, value: int) -> None: ...

    def _pybind11_conduit_v1_(self, *args: Any, **kwargs: Any) -> Any: ...

    def name(self, /) -> str: ...

    def value(self, *args: Any, **kwargs: Any) -> Any: ...


class EvalKey:
    def GetKeyTag(self: EvalKey) -> str: ...

    def SetKeyTag(self: EvalKey, arg0: str) -> None: ...

    def __init__(self: EvalKey) -> None: ...

    def _pybind11_conduit_v1_(self, *args: Any, **kwargs: Any) -> Any: ...


class EvalKeyMap:
    def __init__(self: EvalKeyMap) -> None: ...

    def _pybind11_conduit_v1_(self, *args: Any, **kwargs: Any) -> Any: ...


class ExecutionMode:
    def EXEC_EVALUATION(self, *args: Any, **kwargs: Any) -> Any: ...

    def EXEC_NOISE_ESTIMATION(self, *args: Any, **kwargs: Any) -> Any: ...

    def __init__(self: ExecutionMode, value: int) -> None: ...

    def _pybind11_conduit_v1_(self, *args: Any, **kwargs: Any) -> Any: ...

    def name(self, /) -> str: ...

    def value(self, *args: Any, **kwargs: Any) -> Any: ...


class FHECKKSRNS:
    @overload
    def GetBootstrapDepth(depth: int, levelBudget: List[int], keyDist: SecretKeyDist) -> int: ...
    @overload
    def GetBootstrapDepth(levelBudget: List[int], keyDist: SecretKeyDist) -> int: ...

    def __init__(self: FHECKKSRNS) -> None: ...

    def _pybind11_conduit_v1_(self, *args: Any, **kwargs: Any) -> Any: ...


class Format:
    def COEFFICIENT(self, *args: Any, **kwargs: Any) -> Any: ...

    def EVALUATION(self, *args: Any, **kwargs: Any) -> Any: ...

    def __init__(self: Format, value: int) -> None: ...

    def _pybind11_conduit_v1_(self, *args: Any, **kwargs: Any) -> Any: ...

    def name(self, /) -> str: ...

    def value(self, *args: Any, **kwargs: Any) -> Any: ...


class KEYGEN_MODE:
    def PUB_ENCRYPT(self, *args: Any, **kwargs: Any) -> Any: ...

    def SYM_ENCRYPT(self, *args: Any, **kwargs: Any) -> Any: ...

    def __init__(self: KEYGEN_MODE, value: int) -> None: ...

    def _pybind11_conduit_v1_(self, *args: Any, **kwargs: Any) -> Any: ...

    def name(self, /) -> str: ...

    def value(self, *args: Any, **kwargs: Any) -> Any: ...


class KeyPair:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...

    def _pybind11_conduit_v1_(self, *args: Any, **kwargs: Any) -> Any: ...

    def good(self: KeyPair) -> bool: ...

    def publicKey(self, *args: Any, **kwargs: Any) -> Any: ...

    def secretKey(self, *args: Any, **kwargs: Any) -> Any: ...


class KeySwitchTechnique:
    def BV(self, *args: Any, **kwargs: Any) -> Any: ...

    def HYBRID(self, *args: Any, **kwargs: Any) -> Any: ...

    def INVALID_KS_TECH(self, *args: Any, **kwargs: Any) -> Any: ...

    def __init__(self: KeySwitchTechnique, value: int) -> None: ...

    def _pybind11_conduit_v1_(self, *args: Any, **kwargs: Any) -> Any: ...

    def name(self, /) -> str: ...

    def value(self, *args: Any, **kwargs: Any) -> Any: ...


class LWECiphertext:
    def GetLength(self: LWECiphertext) -> int: ...

    def GetModulus(self: LWECiphertext) -> int: ...

    def __init__(self: LWECiphertext) -> None: ...

    def _pybind11_conduit_v1_(self, *args: Any, **kwargs: Any) -> Any: ...


class LWEPrivateKey:
    def GetLength(self: LWEPrivateKey) -> int: ...

    def __init__(self: LWEPrivateKey) -> None: ...

    def _pybind11_conduit_v1_(self, *args: Any, **kwargs: Any) -> Any: ...


class MultipartyMode:
    def FIXED_NOISE_MULTIPARTY(self, *args: Any, **kwargs: Any) -> Any: ...

    def INVALID_MULTIPARTY_MODE(self, *args: Any, **kwargs: Any) -> Any: ...

    def NOISE_FLOODING_MULTIPARTY(self, *args: Any, **kwargs: Any) -> Any: ...

    def __init__(self: MultipartyMode, value: int) -> None: ...

    def _pybind11_conduit_v1_(self, *args: Any, **kwargs: Any) -> Any: ...

    def name(self, /) -> str: ...

    def value(self, *args: Any, **kwargs: Any) -> Any: ...


class MultiplicationTechnique:
    def BEHZ(self, *args: Any, **kwargs: Any) -> Any: ...

    def HPS(self, *args: Any, **kwargs: Any) -> Any: ...

    def HPSPOVERQ(self, *args: Any, **kwargs: Any) -> Any: ...

    def HPSPOVERQLEVELED(self, *args: Any, **kwargs: Any) -> Any: ...

    def __init__(self: MultiplicationTechnique, value: int) -> None: ...

    def _pybind11_conduit_v1_(self, *args: Any, **kwargs: Any) -> Any: ...

    def name(self, /) -> str: ...

    def value(self, *args: Any, **kwargs: Any) -> Any: ...


class PKESchemeFeature:
    def ADVANCEDSHE(self, *args: Any, **kwargs: Any) -> Any: ...

    def FHE(self, *args: Any, **kwargs: Any) -> Any: ...

    def KEYSWITCH(self, *args: Any, **kwargs: Any) -> Any: ...

    def LEVELEDSHE(self, *args: Any, **kwargs: Any) -> Any: ...

    def MULTIPARTY(self, *args: Any, **kwargs: Any) -> Any: ...

    def PKE(self, *args: Any, **kwargs: Any) -> Any: ...

    def PRE(self, *args: Any, **kwargs: Any) -> Any: ...

    def SCHEMESWITCH(self, *args: Any, **kwargs: Any) -> Any: ...

    def __init__(self: PKESchemeFeature, value: int) -> None: ...

    def _pybind11_conduit_v1_(self, *args: Any, **kwargs: Any) -> Any: ...

    def name(self, /) -> str: ...

    def value(self, *args: Any, **kwargs: Any) -> Any: ...


class ParmType:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...

    def _pybind11_conduit_v1_(self, *args: Any, **kwargs: Any) -> Any: ...


class Plaintext:
    @overload
    def Decode(self: Plaintext) -> bool: ...
    @overload
    def Decode(self: Plaintext, arg0: int, arg1: float, arg2: ScalingTechnique, arg3: ExecutionMode) -> bool: ...

    def Encode(self: Plaintext) -> bool: ...

    def GetCKKSPackedValue(self: Plaintext) -> list[complex]: ...

    def GetCoefPackedValue(self: Plaintext) -> list[int]: ...

    def GetFormattedValues(self: Plaintext, arg0: int) -> str: ...

    def GetLength(self: Plaintext) -> int: ...

    def GetLevel(self: Plaintext) -> int: ...

    def GetLogError(self: Plaintext) -> float: ...

    @overload
    def GetLogPrecision(self: Plaintext) -> float: ...
    @overload
    def GetLogPrecision(self: Plaintext) -> float: ...

    def GetNoiseScaleDeg(self: Plaintext) -> int: ...

    def GetPackedValue(self: Plaintext) -> list[int]: ...

    def GetRealPackedValue(self: Plaintext) -> list[float]: ...

    def GetScalingFactor(self: Plaintext) -> float: ...

    def GetSchemeID(self: Plaintext) -> SCHEME: ...

    def GetSlots(self: Plaintext) -> int: ...

    def GetStringValue(self: Plaintext) -> str: ...

    def HighBound(self: Plaintext) -> int: ...

    def IsEncoded(self: Plaintext) -> bool: ...

    def LowBound(self: Plaintext) -> int: ...

    def SetFormat(self: Plaintext, fmt: Format) -> None: ...

    def SetIntVectorValue(self: Plaintext, arg0: List[int]) -> None: ...

    def SetLength(self: Plaintext, newSize: int) -> None: ...

    def SetLevel(self: Plaintext, arg0: int) -> None: ...

    def SetNoiseScaleDeg(self: Plaintext, arg0: int) -> None: ...

    def SetScalingFactor(self: Plaintext, sf: float) -> None: ...

    def SetSlots(self: Plaintext, arg0: int) -> None: ...

    def SetStringValue(self: Plaintext, arg0: str) -> None: ...

    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...

    def _pybind11_conduit_v1_(self, *args: Any, **kwargs: Any) -> Any: ...


class PrivateKey:
    def GetCryptoContext(self: PrivateKey) -> lbcrypto::CryptoContextImpl<lbcrypto::DCRTPolyImpl<bigintdyn::mubintvec<bigintdyn::ubint<unsigned long long> > > >: ...

    def GetKeyTag(self: PrivateKey) -> str: ...

    def SetKeyTag(self: PrivateKey, arg0: str) -> None: ...

    def __init__(self: PrivateKey) -> None: ...

    def _pybind11_conduit_v1_(self, *args: Any, **kwargs: Any) -> Any: ...


class ProxyReEncryptionMode:
    def FIXED_NOISE_HRA(self, *args: Any, **kwargs: Any) -> Any: ...

    def INDCPA(self, *args: Any, **kwargs: Any) -> Any: ...

    def NOISE_FLOODING_HRA(self, *args: Any, **kwargs: Any) -> Any: ...

    def NOT_SET(self, *args: Any, **kwargs: Any) -> Any: ...

    def __init__(self: ProxyReEncryptionMode, value: int) -> None: ...

    def _pybind11_conduit_v1_(self, *args: Any, **kwargs: Any) -> Any: ...

    def name(self, /) -> str: ...

    def value(self, *args: Any, **kwargs: Any) -> Any: ...


class PublicKey:
    def GetKeyTag(self: PublicKey) -> str: ...

    def SetKeyTag(self: PublicKey, arg0: str) -> None: ...

    def __init__(self: PublicKey) -> None: ...

    def _pybind11_conduit_v1_(self, *args: Any, **kwargs: Any) -> Any: ...


class SCHEME:
    def BFVRNS_SCHEME(self, *args: Any, **kwargs: Any) -> Any: ...

    def BGVRNS_SCHEME(self, *args: Any, **kwargs: Any) -> Any: ...

    def CKKSRNS_SCHEME(self, *args: Any, **kwargs: Any) -> Any: ...

    def INVALID_SCHEME(self, *args: Any, **kwargs: Any) -> Any: ...

    def __init__(self: SCHEME, value: int) -> None: ...

    def _pybind11_conduit_v1_(self, *args: Any, **kwargs: Any) -> Any: ...

    def name(self, /) -> str: ...

    def value(self, *args: Any, **kwargs: Any) -> Any: ...


class SERBINARY:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...

    def _pybind11_conduit_v1_(self, *args: Any, **kwargs: Any) -> Any: ...


class SERJSON:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...

    def _pybind11_conduit_v1_(self, *args: Any, **kwargs: Any) -> Any: ...


class ScalingTechnique:
    def COMPOSITESCALINGAUTO(self, *args: Any, **kwargs: Any) -> Any: ...

    def COMPOSITESCALINGMANUAL(self, *args: Any, **kwargs: Any) -> Any: ...

    def FIXEDAUTO(self, *args: Any, **kwargs: Any) -> Any: ...

    def FIXEDMANUAL(self, *args: Any, **kwargs: Any) -> Any: ...

    def FLEXIBLEAUTO(self, *args: Any, **kwargs: Any) -> Any: ...

    def FLEXIBLEAUTOEXT(self, *args: Any, **kwargs: Any) -> Any: ...

    def INVALID_RS_TECHNIQUE(self, *args: Any, **kwargs: Any) -> Any: ...

    def NORESCALE(self, *args: Any, **kwargs: Any) -> Any: ...

    def __init__(self: ScalingTechnique, value: int) -> None: ...

    def _pybind11_conduit_v1_(self, *args: Any, **kwargs: Any) -> Any: ...

    def name(self, /) -> str: ...

    def value(self, *args: Any, **kwargs: Any) -> Any: ...


class SchSwchParams:
    def GetArbitraryFunctionEvaluation(self: SchSwchParams) -> bool: ...

    def GetBStepLTrCKKStoFHEW(self: SchSwchParams) -> int: ...

    def GetBStepLTrFHEWtoCKKS(self: SchSwchParams) -> int: ...

    def GetBatchSize(self: SchSwchParams) -> int: ...

    def GetComputeArgmin(self: SchSwchParams) -> bool: ...

    def GetCtxtModSizeFHEWIntermedSwch(self: SchSwchParams) -> int: ...

    def GetCtxtModSizeFHEWLargePrec(self: SchSwchParams) -> int: ...

    def GetInitialCKKSModulus(self: SchSwchParams) -> intnat::NativeIntegerT<unsigned long long>: ...

    def GetLevelLTrCKKStoFHEW(self: SchSwchParams) -> int: ...

    def GetLevelLTrFHEWtoCKKS(self: SchSwchParams) -> int: ...

    def GetNumSlotsCKKS(self: SchSwchParams) -> int: ...

    def GetNumValues(self: SchSwchParams) -> int: ...

    def GetOneHotEncoding(self: SchSwchParams) -> bool: ...

    def GetRingDimension(self: SchSwchParams) -> int: ...

    def GetScalingModSize(self: SchSwchParams) -> int: ...

    def GetSecurityLevelCKKS(self: SchSwchParams) -> SecurityLevel: ...

    def GetSecurityLevelFHEW(self: SchSwchParams) -> BINFHE_PARAMSET: ...

    def GetUseAltArgmin(self: SchSwchParams) -> bool: ...

    def GetUseDynamicModeFHEW(self: SchSwchParams) -> bool: ...

    def SetArbitraryFunctionEvaluation(self: SchSwchParams, arg0: bool) -> None: ...

    def SetBStepLTrCKKStoFHEW(self: SchSwchParams, arg0: int) -> None: ...

    def SetBStepLTrFHEWtoCKKS(self: SchSwchParams, arg0: int) -> None: ...

    def SetBatchSize(self: SchSwchParams, arg0: int) -> None: ...

    def SetComputeArgmin(self: SchSwchParams, arg0: bool) -> None: ...

    def SetCtxtModSizeFHEWIntermedSwch(self: SchSwchParams, arg0: int) -> None: ...

    def SetCtxtModSizeFHEWLargePrec(self: SchSwchParams, arg0: int) -> None: ...

    def SetInitialCKKSModulus(self: SchSwchParams, arg0: intnat::NativeIntegerT<unsigned long long>) -> None: ...

    def SetLevelLTrCKKStoFHEW(self: SchSwchParams, arg0: int) -> None: ...

    def SetLevelLTrFHEWtoCKKS(self: SchSwchParams, arg0: int) -> None: ...

    def SetNumSlotsCKKS(self: SchSwchParams, arg0: int) -> None: ...

    def SetNumValues(self: SchSwchParams, arg0: int) -> None: ...

    def SetOneHotEncoding(self: SchSwchParams, arg0: bool) -> None: ...

    def SetRingDimension(self: SchSwchParams, arg0: int) -> None: ...

    def SetScalingModSize(self: SchSwchParams, arg0: int) -> None: ...

    def SetSecurityLevelCKKS(self: SchSwchParams, arg0: SecurityLevel) -> None: ...

    def SetSecurityLevelFHEW(self: SchSwchParams, arg0: BINFHE_PARAMSET) -> None: ...

    def SetUseAltArgmin(self: SchSwchParams, arg0: bool) -> None: ...

    def SetUseDynamicModeFHEW(self: SchSwchParams, arg0: bool) -> None: ...

    def __init__(self: SchSwchParams) -> None: ...

    def _pybind11_conduit_v1_(self, *args: Any, **kwargs: Any) -> Any: ...


class SecretKeyDist:
    def GAUSSIAN(self, *args: Any, **kwargs: Any) -> Any: ...

    def SPARSE_ENCAPSULATED(self, *args: Any, **kwargs: Any) -> Any: ...

    def SPARSE_TERNARY(self, *args: Any, **kwargs: Any) -> Any: ...

    def UNIFORM_TERNARY(self, *args: Any, **kwargs: Any) -> Any: ...

    def __init__(self: SecretKeyDist, value: int) -> None: ...

    def _pybind11_conduit_v1_(self, *args: Any, **kwargs: Any) -> Any: ...

    def name(self, /) -> str: ...

    def value(self, *args: Any, **kwargs: Any) -> Any: ...


class SecurityLevel:
    def HEStd_128_classic(self, *args: Any, **kwargs: Any) -> Any: ...

    def HEStd_128_quantum(self, *args: Any, **kwargs: Any) -> Any: ...

    def HEStd_192_classic(self, *args: Any, **kwargs: Any) -> Any: ...

    def HEStd_192_quantum(self, *args: Any, **kwargs: Any) -> Any: ...

    def HEStd_256_classic(self, *args: Any, **kwargs: Any) -> Any: ...

    def HEStd_256_quantum(self, *args: Any, **kwargs: Any) -> Any: ...

    def HEStd_NotSet(self, *args: Any, **kwargs: Any) -> Any: ...

    def __init__(self: SecurityLevel, value: int) -> None: ...

    def _pybind11_conduit_v1_(self, *args: Any, **kwargs: Any) -> Any: ...

    def name(self, /) -> str: ...

    def value(self, *args: Any, **kwargs: Any) -> Any: ...


